# Generated by Django 4.2 on 2023-09-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatroom_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroommessages",
            name="room",
        ),
        migrations.RemoveField(
            model_name="chatroommessages",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="ChatRoomMessages",
        ),
    ]
